# Generated by Django 5.1.5 on 2025-02-01 17:17

import django.db.models.deletion
import santry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='sample food item', max_length=100)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('image', models.TextField(null=True)),
                ('category', models.CharField(default='Uncategorized', max_length=50, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('unit', models.CharField(default='pieces', max_length=20)),
                ('expiry_date', models.DateField(default=santry.models.get_default_expiry_date)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='sample recipe', max_length=100)),
                ('description', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('instructions', models.TextField(null=True)),
                ('dietary_restrictions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New User', max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('profile_picture_url', models.TextField(null=True)),
                ('dietary_preferences', models.TextField(null=True)),
                ('santry_green_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(default='sample tag', max_length=100)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='santry.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(null=True)),
                ('unit', models.CharField(default='', max_length=20, null=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santry.fooditem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='santry.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggested_on', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='santry.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_suggestions', to='santry.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('triggered_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='santry.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='santry.user')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='user',
            field=models.ForeignKey(default=santry.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to='santry.user'),
        ),
    ]
